@echo off
echo 🚀 PDFTron WebViewer Environment Setup
echo =====================================
echo.

set /p LICENSE_KEY="Enter your PDFTron license key (get it from https://www.pdftron.com/): "

if "%LICENSE_KEY%"=="" (
    echo ❌ License key is required. Please run the script again with a valid key.
    pause
    exit /b 1
)

echo.
echo 📁 Creating environment files...

REM Create frontend .env.local
echo # React App Environment Variables > elearning\.env.local
echo # Generated by setup script >> elearning\.env.local
echo. >> elearning\.env.local
echo # API Configuration >> elearning\.env.local
echo REACT_APP_API_URL=http://localhost:5000 >> elearning\.env.local
echo. >> elearning\.env.local
echo # PDFTron WebViewer License Key >> elearning\.env.local
echo REACT_APP_PDFTRON_LICENSE_KEY=%LICENSE_KEY% >> elearning\.env.local
echo. >> elearning\.env.local
echo # App Configuration >> elearning\.env.local
echo REACT_APP_NAME=Excellence Coaching Hub - eLearning >> elearning\.env.local
echo REACT_APP_VERSION=1.0.0 >> elearning\.env.local
echo REACT_APP_ENVIRONMENT=development >> elearning\.env.local

echo ✅ Created elearning/.env.local

REM Create backend .env
echo # Backend Environment Variables > backend\.env
echo # Generated by setup script >> backend\.env
echo. >> backend\.env
echo # Database Configuration >> backend\.env
echo MONGODB_URI=mongodb://localhost:27017/excellencecoachinghub >> backend\.env
echo. >> backend\.env
echo # JWT Configuration >> backend\.env
echo JWT_SECRET=your_jwt_secret_here_%RANDOM% >> backend\.env
echo JWT_EXPIRE=7d >> backend\.env
echo. >> backend\.env
echo # Server Configuration >> backend\.env
echo NODE_ENV=development >> backend\.env
echo PORT=5000 >> backend\.env
echo. >> backend\.env
echo # CORS Configuration >> backend\.env
echo FRONTEND_URL=http://localhost:3000 >> backend\.env
echo. >> backend\.env
echo # Rate Limiting >> backend\.env
echo RATE_LIMIT_WINDOW_MS=900000 >> backend\.env
echo RATE_LIMIT_MAX_REQUESTS=100 >> backend\.env
echo. >> backend\.env
echo # PDFTron License Key >> backend\.env
echo PDFTRON_LICENSE_KEY=%LICENSE_KEY% >> backend\.env

echo ✅ Created backend/.env

echo.
echo 🎉 Environment setup complete!
echo.
echo 📝 Next steps:
echo 1. Start the backend server: cd backend ^&^& npm run dev
echo 2. Start the frontend server: cd elearning ^&^& npm start
echo 3. Test the enhanced material viewer with any document format
echo.
echo 🔑 Your PDFTron license key has been added to both environment files.
echo 📚 Check PDFTRON_ENVIRONMENT_SETUP.md for more details.

pause
