#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setupEnvironment() {
  console.log('🚀 PDFTron WebViewer Environment Setup');
  console.log('=====================================\n');

  // Get PDFTron license key
  const licenseKey = await question('Enter your PDFTron license key (get it from https://www.pdftron.com/): ');
  
  if (!licenseKey || licenseKey.trim() === '') {
    console.log('❌ License key is required. Please run the script again with a valid key.');
    rl.close();
    return;
  }

  // Frontend environment file
  const frontendEnvPath = path.join(__dirname, 'elearning', '.env.local');
  const frontendEnvContent = `# React App Environment Variables
# Generated by setup script

# API Configuration
REACT_APP_API_URL=http://localhost:5000

# PDFTron WebViewer License Key
REACT_APP_PDFTRON_LICENSE_KEY=${licenseKey.trim()}

# App Configuration
REACT_APP_NAME=Excellence Coaching Hub - eLearning
REACT_APP_VERSION=1.0.0
REACT_APP_ENVIRONMENT=development
`;

  // Backend environment file
  const backendEnvPath = path.join(__dirname, 'backend', '.env');
  const backendEnvContent = `# Backend Environment Variables
# Generated by setup script

# Database Configuration
MONGODB_URI=mongodb://localhost:27017/excellencecoachinghub

# JWT Configuration
JWT_SECRET=your_jwt_secret_here_${Date.now()}
JWT_EXPIRE=7d

# Server Configuration
NODE_ENV=development
PORT=5000

# CORS Configuration
FRONTEND_URL=http://localhost:3000

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# PDFTron License Key (for backend if needed)
PDFTRON_LICENSE_KEY=${licenseKey.trim()}

# Add other environment variables as needed
# CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name
# CLOUDINARY_API_KEY=your_cloudinary_api_key
# CLOUDINARY_API_SECRET=your_cloudinary_api_secret
`;

  try {
    // Create frontend .env.local
    fs.writeFileSync(frontendEnvPath, frontendEnvContent);
    console.log('✅ Created elearning/.env.local');

    // Create backend .env
    fs.writeFileSync(backendEnvPath, backendEnvContent);
    console.log('✅ Created backend/.env');

    console.log('\n🎉 Environment setup complete!');
    console.log('\n📝 Next steps:');
    console.log('1. Start the backend server: cd backend && npm run dev');
    console.log('2. Start the frontend server: cd elearning && npm start');
    console.log('3. Test the enhanced material viewer with any document format');
    
    console.log('\n🔑 Your PDFTron license key has been added to both environment files.');
    console.log('📚 Check PDFTRON_ENVIRONMENT_SETUP.md for more details.');

  } catch (error) {
    console.error('❌ Error creating environment files:', error.message);
  }

  rl.close();
}

// Run the setup
setupEnvironment().catch(console.error);
